"""Note generation for Mid Brain cognitive outputs."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any
from uuid import uuid4

from mid_brain.obsidian.frontmatter import FrontmatterType, MidBrainFrontmatter
from mid_brain.obsidian.vault_manager import VaultManager


@dataclass(slots=True)
class NoteContext:
    """Context for note generation."""

    trace_id: str
    project_id: str | None = None
    source_brain: str = "mid-brain"
    cognitive_phase: str | None = None
    confidence: float = 0.5
    importance: float = 0.5
    tags: list[str] = None
    provenance: dict[str, Any] = None
    related_entities: list[str] = None

    def __post_init__(self):
        if self.tags is None:
            self.tags = []
        if self.provenance is None:
            self.provenance = {}
        if self.related_entities is None:
            self.related_entities = []


class NoteGenerator:
    """Generates Obsidian notes from Mid Brain cognitive outputs."""

    def __init__(self, vault_manager: VaultManager) -> None:
        self.vault = vault_manager

    # ------------------------------------------------------------------ Questions
    def generate_question_note(
        self,
        question: str,
        context: NoteContext,
        understanding: dict[str, Any] | None = None,
    ) -> str:
        """Generate a question note."""
        fm = MidBrainFrontmatter(
            title=f"Question: {question[:80]}",
            type=FrontmatterType.QUESTION,
            project=context.project_id,
            tags=["question"] + context.tags,
            importance=context.importance,
            confidence=context.confidence,
            trace_id=context.trace_id,
            source_brain=context.source_brain,
            cognitive_phase=context.cognitive_phase or "UNDERSTAND",
            provenance=context.provenance,
            related_entities=context.related_entities,
        )

        body_parts = [
            f"# {question}",
            "",
            f"**Trace ID:** `{context.trace_id}`",
            f"**Project:** {context.project_id or 'N/A'}",
            f"**Source:** {context.source_brain}",
            f"**Phase:** {context.cognitive_phase or 'UNDERSTAND'}",
            "",
            "## Understanding",
        ]

        if understanding:
            body_parts.append(f"- **Type:** {understanding.get('type', 'unknown')}")
            body_parts.append(f"- **Complexity:** {understanding.get('complexity', 'unknown')}")
            if understanding.get("entities"):
                body_parts.append(f"- **Entities:** {', '.join(understanding['entities'])}")
        else:
            body_parts.append("*No detailed analysis available*")

        body_parts.extend([
            "",
            "---",
            f"*Generated by Mid Brain at {datetime.now().isoformat()}*",
        ])

        return self._create_note(fm, "\n".join(body_parts))

    # ------------------------------------------------------------------ Answers
    def generate_answer_note(
        self,
        question: str,
        answer: str,
        context: NoteContext,
        confidence: float,
        sources: dict[str, Any],
    ) -> str:
        """Generate an answer/synthesis note."""
        fm = MidBrainFrontmatter(
            title=f"Answer: {question[:80]}",
            type=FrontmatterType.ANSWER,
            project=context.project_id,
            tags=["answer", "synthesis"] + context.tags,
            importance=context.importance,
            confidence=confidence,
            trace_id=context.trace_id,
            source_brain=context.source_brain,
            cognitive_phase=context.cognitive_phase or "SYNTHESIS",
            provenance=context.provenance,
            related_entities=context.related_entities,
        )

        body_parts = [
            f"# Answer: {question}",
            "",
            f"**Trace ID:** `{context.trace_id}`",
            f"**Confidence:** {confidence:.2%}",
            f"**Project:** {context.project_id or 'N/A'}",
            "",
            "## Answer",
            answer,
            "",
            "## Sources",
        ]

        if sources.get("first_brain"):
            body_parts.append("### First Brain (Experience)")
            body_parts.append(sources["first_brain"][:500])
            body_parts.append("")

        if sources.get("second_brain"):
            body_parts.append("### Second Brain (Knowledge)")
            body_parts.append(sources["second_brain"][:500])
            body_parts.append("")

        if sources.get("mid_brain_memory"):
            body_parts.append("### Mid Brain Memory")
            memories = sources["mid_brain_memory"].get("results", [])
            for mem in memories[:3]:
                body_parts.append(f"- {mem.get('content', '')[:200]}")
            body_parts.append("")

        body_parts.extend([
            "---",
            f"*Generated by Mid Brain at {datetime.now().isoformat()}*",
        ])

        return self._create_note(fm, "\n".join(body_parts))

    # ------------------------------------------------------------------ Knowledge
    def generate_knowledge_note(
        self,
        content: str,
        kind: str,
        context: NoteContext,
        knowledge_id: str | None = None,
        version: int = 1,
        status: str = "candidate",
    ) -> str:
        """Generate a knowledge note."""
        type_map = {
            "fact": FrontmatterType.KNOWLEDGE,
            "decision": FrontmatterType.DECISION,
            "lesson": FrontmatterType.LESSON,
            "strategy": FrontmatterType.STRATEGY,
            "experience": FrontmatterType.EXPERIENCE,
        }

        fm = MidBrainFrontmatter(
            title=f"{kind.title()}: {content[:80]}",
            type=type_map.get(kind, FrontmatterType.KNOWLEDGE),
            project=context.project_id,
            tags=[kind] + context.tags,
            importance=context.importance,
            confidence=context.confidence,
            trace_id=context.trace_id,
            source_brain=context.source_brain,
            cognitive_phase=context.cognitive_phase or "KNOWLEDGE",
            provenance={**context.provenance, "knowledge_id": knowledge_id, "version": version, "status": status},
            related_entities=context.related_entities,
        )

        body_parts = [
            f"# {kind.title()}: {content[:100]}",
            "",
            f"**Knowledge ID:** `{knowledge_id or 'new'}`",
            f"**Version:** {version}",
            f"**Status:** {status}",
            f"**Trace ID:** `{context.trace_id}`",
            "",
            "## Content",
            content,
            "",
            "---",
            f"*Generated by Mid Brain at {datetime.now().isoformat()}*",
        ]

        return self._create_note(fm, "\n".join(body_parts))

    # ------------------------------------------------------------------ Conflict
    def generate_conflict_note(
        self,
        claim_a: str,
        claim_b: str,
        context: NoteContext,
        evidence_a: list[str] | None = None,
        evidence_b: list[str] | None = None,
        severity: str = "medium",
        resolution: str | None = None,
    ) -> str:
        """Generate a conflict note."""
        fm = MidBrainFrontmatter(
            title=f"Conflict: {claim_a[:50]} vs {claim_b[:50]}",
            type=FrontmatterType.CONFLICT,
            project=context.project_id,
            tags=["conflict", severity] + context.tags,
            importance=0.8,
            confidence=context.confidence,
            trace_id=context.trace_id,
            source_brain=context.source_brain,
            cognitive_phase=context.cognitive_phase or "CONFLICT_DETECTION",
            provenance={**context.provenance, "severity": severity, "resolution": resolution},
            related_entities=context.related_entities,
        )

        body_parts = [
            f"# Conflict: {claim_a[:100]} vs {claim_b[:100]}",
            "",
            f"**Trace ID:** `{context.trace_id}`",
            f"**Severity:** {severity}",
            f"**Resolution:** {resolution or 'Pending'}",
            "",
            "## Claim A",
            claim_a,
            "",
            "## Claim B",
            claim_b,
            "",
        ]

        if evidence_a:
            body_parts.append("## Evidence for A")
            for e in evidence_a:
                body_parts.append(f"- {e}")
            body_parts.append("")

        if evidence_b:
            body_parts.append("## Evidence for B")
            for e in evidence_b:
                body_parts.append(f"- {e}")
            body_parts.append("")

        body_parts.extend([
            "---",
            f"*Generated by Mid Brain at {datetime.now().isoformat()}*",
        ])

        return self._create_note(fm, "\n".join(body_parts))

    # ------------------------------------------------------------------ Reflection
    def generate_reflection_note(
        self,
        question: str,
        answer: str,
        reflection_data: dict[str, Any],
        context: NoteContext,
    ) -> str:
        """Generate a reflection note."""
        fm = MidBrainFrontmatter(
            title=f"Reflection: {question[:80]}",
            type=FrontmatterType.REFLECTION,
            project=context.project_id,
            tags=["reflection"] + context.tags,
            importance=context.importance,
            confidence=context.confidence,
            trace_id=context.trace_id,
            source_brain=context.source_brain,
            cognitive_phase=context.cognitive_phase or "REFLECTION",
            provenance={**context.provenance, "reflection_id": reflection_data.get("reflection_id")},
            related_entities=context.related_entities,
        )

        body_parts = [
            f"# Reflection: {question}",
            "",
            f"**Trace ID:** `{context.trace_id}`",
            f"**Reflection ID:** `{reflection_data.get('reflection_id', 'N/A')}`",
            "",
            "## Original Q&A",
            f"**Q:** {question}",
            f"**A:** {answer}",
            "",
        ]

        for key, value in reflection_data.items():
            if key != "reflection_id" and value:
                body_parts.append(f"## {key.replace('_', ' ').title()}")
                if isinstance(value, list):
                    for v in value:
                        body_parts.append(f"- {v}")
                else:
                    body_parts.append(str(value))
                body_parts.append("")

        body_parts.extend([
            "---",
            f"*Generated by Mid Brain at {datetime.now().isoformat()}*",
        ])

        return self._create_note(fm, "\n".join(body_parts))

    # ------------------------------------------------------------------ Learning
    def generate_learning_note(
        self,
        learning_items: list[dict[str, Any]],
        context: NoteContext,
    ) -> str:
        """Generate a learning note from extracted learnings."""
        fm = MidBrainFrontmatter(
            title=f"Learning: {len(learning_items)} items",
            type=FrontmatterType.LESSON,
            project=context.project_id,
            tags=["learning"] + context.tags,
            importance=context.importance,
            confidence=context.confidence,
            trace_id=context.trace_id,
            source_brain=context.source_brain,
            cognitive_phase=context.cognitive_phase or "LEARNING",
            provenance=context.provenance,
            related_entities=context.related_entities,
        )

        body_parts = [
            "# Learning Session",
            "",
            f"**Trace ID:** `{context.trace_id}`",
            f"**Items:** {len(learning_items)}",
            "",
        ]

        for i, item in enumerate(learning_items, 1):
            body_parts.append(f"## Item {i}: {item.get('learning_type', 'unknown').title()}")
            body_parts.append(f"**Content:** {item.get('content', 'N/A')}")
            body_parts.append(f"**Confidence:** {item.get('confidence', 0):.2%}")
            if item.get("tags"):
                body_parts.append(f"**Tags:** {', '.join(item['tags'])}")
            body_parts.append("")

        body_parts.extend([
            "---",
            f"*Generated by Mid Brain at {datetime.now().isoformat()}*",
        ])

        return self._create_note(fm, "\n".join(body_parts))

    # ------------------------------------------------------------------ Agent Task/Result
    def generate_task_note(
        self,
        task_spec: dict[str, Any],
        context: NoteContext,
    ) -> str:
        """Generate an agent task note."""
        fm = MidBrainFrontmatter(
            title=f"Task: {task_spec.get('objective', 'Unknown')[:80]}",
            type=FrontmatterType.TASK,
            project=context.project_id,
            tags=["task", task_spec.get("priority", "medium")] + context.tags,
            importance=0.7,
            confidence=0.5,
            trace_id=context.trace_id,
            source_brain=context.source_brain,
            cognitive_phase=context.cognitive_phase or "PLANNING",
            provenance={**context.provenance, "task_id": task_spec.get("task_id")},
            related_entities=context.related_entities,
        )

        body_parts = [
            f"# Task: {task_spec.get('objective', 'Unknown')}",
            "",
            f"**Task ID:** `{task_spec.get('task_id', uuid4().hex[:12])}`",
            f"**Trace ID:** `{context.trace_id}`",
            f"**Priority:** {task_spec.get('priority', 'medium')}",
            f"**Risk Level:** {task_spec.get('risk_level', 'low')}",
            "",
            "## Description",
            task_spec.get("description", "N/A"),
            "",
            "## Context",
            task_spec.get("context", "N/A"),
            "",
            "## Constraints",
        ]

        for c in task_spec.get("constraints", []):
            body_parts.append(f"- {c}")

        body_parts.extend([
            "",
            "## Expected Output",
            task_spec.get("expected_output", "N/A"),
            "",
            "## Tools Allowed",
        ])

        for t in task_spec.get("tools_allowed", []):
            body_parts.append(f"- {t}")

        body_parts.extend([
            "",
            "## Validation Rules",
        ])

        for r in task_spec.get("validation_rules", []):
            body_parts.append(f"- {r}")

        body_parts.extend([
            "",
            "---",
            f"*Generated by Mid Brain at {datetime.now().isoformat()}*",
        ])

        return self._create_note(fm, "\n".join(body_parts))

    def generate_agent_result_note(
        self,
        task_spec: dict[str, Any],
        result: dict[str, Any],
        context: NoteContext,
    ) -> str:
        """Generate an agent execution result note."""
        success = result.get("success", False)
        fm = MidBrainFrontmatter(
            title=f"Agent Result: {task_spec.get('objective', 'Unknown')[:60]} ({'✓' if success else '✗'})",
            type=FrontmatterType.AGENT_RESULT,
            project=context.project_id,
            tags=["agent-result", "success" if success else "failure"] + context.tags,
            importance=0.7,
            confidence=1.0 if success else 0.3,
            trace_id=context.trace_id,
            source_brain=context.source_brain,
            cognitive_phase=context.cognitive_phase or "EXECUTION",
            provenance={**context.provenance, "task_id": task_spec.get("task_id")},
            related_entities=context.related_entities,
        )

        body_parts = [
            "# Agent Result",
            "",
            f"**Task ID:** `{task_spec.get('task_id', 'N/A')}`",
            f"**Trace ID:** `{context.trace_id}`",
            f"**Success:** {'Yes' if success else 'No'}",
            "",
            "## Objective",
            task_spec.get("objective", "N/A"),
            "",
            "## Result",
        ]

        if success:
            body_parts.append(result.get("output", "No output"))
        else:
            body_parts.append(f"**Error:** {result.get('error', 'Unknown error')}")
            if result.get("traceback"):
                body_parts.append("```")
                body_parts.append(result["traceback"])
                body_parts.append("```")

        body_parts.extend([
            "",
            "## Files Changed",
        ])

        for f in result.get("files_changed", []):
            body_parts.append(f"- {f}")

        body_parts.extend([
            "",
            "## Commands Run",
        ])

        for c in result.get("commands", []):
            body_parts.append(f"- `{c}`")

        body_parts.extend([
            "",
            "## Test Results",
            result.get("test_results", "N/A"),
            "",
            "---",
            f"*Generated by Mid Brain at {datetime.now().isoformat()}*",
        ])

        return self._create_note(fm, "\n".join(body_parts))

    # ------------------------------------------------------------------ Feedback
    def generate_feedback_note(
        self,
        feedback_data: dict[str, Any],
        context: NoteContext,
    ) -> str:
        """Generate a human feedback note."""
        fm = MidBrainFrontmatter(
            title=f"Feedback: {feedback_data.get('type', 'unknown').title()}",
            type=FrontmatterType.FEEDBACK,
            project=context.project_id,
            tags=["feedback", feedback_data.get("type", "unknown")] + context.tags,
            importance=0.8,
            confidence=0.9,
            trace_id=context.trace_id,
            source_brain=context.source_brain,
            cognitive_phase=context.cognitive_phase or "HUMAN_FEEDBACK",
            provenance={**context.provenance, "feedback_id": feedback_data.get("feedback_id")},
            related_entities=context.related_entities,
        )

        body_parts = [
            "# Human Feedback",
            "",
            f"**Feedback ID:** `{feedback_data.get('feedback_id', uuid4().hex[:12])}`",
            f"**Trace ID:** `{context.trace_id}`",
            f"**Type:** {feedback_data.get('type', 'unknown')}",
            f"**Source:** {feedback_data.get('source', 'human')}",
            f"**Destination:** {feedback_data.get('destination', 'mid-brain')}",
            "",
            "## Content",
            feedback_data.get("content", "N/A"),
            "",
        ]

        if feedback_data.get("context"):
            body_parts.append("## Context")
            body_parts.append(str(feedback_data["context"]))
            body_parts.append("")

        body_parts.extend([
            "---",
            f"*Recorded by Mid Brain at {datetime.now().isoformat()}*",
        ])

        return self._create_note(fm, "\n".join(body_parts))

    # ------------------------------------------------------------------ Helper
    def _create_note(self, frontmatter: MidBrainFrontmatter, body: str) -> str:
        """Create full note with frontmatter."""
        return f"---\n{frontmatter.to_yaml()}\n---\n\n{body}"
